### PR TITLE
feat(header): add header component

### PR DESCRIPTION
**Pull request by orlando**
**What:** add header component

**Why:** To have the latest header component render correctly

**How:**

- Add partials in the application layout to render the header

**Media:**

image

**gif**

### CODE REVIEW

**Comment by orlando** [comment]
Hey @thiagodemellobueno, here's the PR to integrate the header

**Review by hissingpanda — APPROVED** [review]
LGTM

**Comment by thiagodemellobueno** [comment]
Let's not merge this one til we launched the new nav elsewhere.

Talked to @hissingpanda and we're gonna issue one with the 2.5.0.nav for now

**Comment by thiagodemellobueno** [comment]
Thank you @orlando

**Comment by duranmla** [comment]
I will update this as we need to change `host` by `returnurl`

**Pull request merged**
