### PR TITLE
Feat/design enhancements for homepage

### PR DESCRIPTION
**Pull request by castrolem**
**What:**
Design enhancements for homepage

**Why:**
We needed to change some of the CSS to favor legibility and push users better towards clicking on our CTAs

**How:**
Changing sizing and colors of certain elements and adding products and links to our store.

## Screenshots
Screenshot_2019-11-16 Debt Collective - Fundraising

Screenshot_2019-11-19 Debt Collective - Fundraising

### CODE REVIEW

**Comment by orlando** [comment]
Hey @castrolem, 

Can you please add screenshots on how it looks on mobile?

Thanks!

**Comment by castrolem** [comment]
@orlando updated

**Comment by orlando** [comment]
I like a lot more about how it looks on mobile than on desktop. Let's think about how we can improve this later.

LGTM

**Review by orlando — APPROVED** [review]
LGTM

**Pull request merged**
